# Generated by Django 2.1.6 on 2019-04-30 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creationApp', '0001_initial'),
        ('preparationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(blank=True, related_name='members', to='creationApp.Answer')),
                ('current_puzzle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='creationApp.Puzzle')),
                ('hints', models.ManyToManyField(blank=True, related_name='members', to='creationApp.Hint')),
                ('puzzles', models.ManyToManyField(blank=True, related_name='members', to='creationApp.Puzzle')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparationApp.Quest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparationApp.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'quest')},
        ),
    ]
