# Generated by Django 2.1.7 on 2019-03-27 06:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preparationApp', '0004_invite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('new_member', 'team')},
        ),
    ]
