# Generated by Django 2.1.7 on 2019-03-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preparationApp', '0005_auto_20190327_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparationApp.Quest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparationApp.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('quest', 'team')},
        ),
    ]
